{% set name = "dataclasses-avroschema" %}
{% set version = "0.65.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dataclasses_avroschema-{{ version }}.tar.gz
  sha256: 3ca69425ce8ddaa79c736ee5138997f93b9f0a37c87164e05d16fa0d4d5d6fbb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.8.0,<4.0.0
    - fastavro >=1.7.3,<2.0.0
    - dacite >=1.8.0,<2.0.0
    - casefy >=0.1.7,<0.2.0
    - typing-extensions >=4.2.0,<5.0.0
    - python-dateutil >=2.7.0,<3.0.0
    - inflection >=0.5.1,<0.6.0
  run_constrained:
    - faker >=26.0.0,<27.0.0
    - faust-streaming >=0.10.11,<0.12.0
    - pydantic >=2.4.2,<3.0.0
    - dc-avro >=0.6.4,<0.9.0

test:
  imports:
    - dataclasses_avroschema
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/dataclasses-avroschema/
  summary: Generate Avro Schemas from Python classes. Serialize/Deserialize python instances with avro schemas
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcosschroh
